[package]
name = "wishing-star"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = { version = "2.9.7", features = ["json"] }
serde = "1.0.203"
serde_yml = "0.0.10"
log = "0.4.22"
simple_logger = "5.0.0"
maud = "0.26.0"
