[package]
name = "shopping-list"
version = "3.0.0"
edition = "2021"

[dependencies]
ureq = { version = "2.10.0", features = ["json"] }
serde = "1.0.203"
serde_yml = "0.0.11"
log = "0.4.22"
simple_logger = "5.0.0"
maud = "0.26.0"
md5 = "0.7.0"
