# Enter your name here, it will show up in the UI:
name: The Starscouts

# Enable deploying to Vercel
vercel: true

# Set the default currency
currency: €

# Show the Frequently asked questions section
faq: true

# Enable importing/exporting user data
export: true

# Show a notice on the website
#notice: Stuff is wrong!

# Configure the default Steam module
steam:
  # Enable the module
  enable: true

  # The name of the module in the UI
  name: Video games

  # Your Steam user ID or profile name
  id: Starscouts

  # The recommendation index of Steam
  recommend: 0

  # Notes to associate with Steam games
  notes:
    219890: A friend recommended this game, don't know much about it.

# Add custom items to the wishlist
custom:

  # Create a new group
  tech:

    # Whether the group should be considered not safe for work
    nsfw: false

    # Name for the group
    name: Technology and multimedia

    # Recommendation index for the group
    recommend: 2

    # Items that are part of this group
    items:
      # Name for an item
      - name: Audio-Technica ATH-M50x Black

      # Link to the item page
        link: https://www.amazon.fr/dp/B00HVLUR86

      # Price of the item in cents
        price: 14300

      # If using a custom currency, specify the format here
        unit: "$ %"

      # URL to the item image
        image: https://m.media-amazon.com/images/I/71BR7ivLOAL._AC_SY879_.jpg

      # Source of the item to display in the UI
        source: Amazon.fr

      # Tags associated with the item
        tags:
          - Headphones
          - Studio equipment
          - Professional audio

      # Note associated with the item
        note: Our current headphones are (slowly) breaking down (pieces of plastic are falling) and are not really that great quality. We would appreciate having higher quality headphones for listening to and making music.
